apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todoapp-deployment-green
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: todoapp
        role: green
    spec:
      containers:
      - name: todoapp-container
        image: tomcat
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
